services:
  db:
    image: postgres:16-alpine
    container_name: ez_shop_db
    env_file:
      - .env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    container_name: ez_shop_redis
    command: redis-server --maxmemory 300mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - django_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: jisan11/ez_shop_web:latest
    container_name: ez_shop_web
    user: "0:0"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 180 --reload --access-logfile - --error-logfile - --log-level info"
    ports:
      - "8007:8000"
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - django_net
    restart: unless-stopped
    healthcheck:
      test: >
        python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/').read()"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  postgres_data:
  redis_data:

networks:
  django_net:
    driver: bridge
